Added support for severity.
codereligion/bugsnag-logback pull request #10
Opened 2017-06-07 09:15 UTC by Niaobu

Potential fix for issue #9.
The solution is pretty naive and does not worry about other log levels than error, warning, info.

2017-06-07 12:42 UTC, Niaobu commented
Hey @SierraGolf, I gave this issue a go. First time submitting a pull request and a bit confused about the CI and tests in general. The changes I proposed are pretty straightforward. The tests are all green on my machine, and the CI build complains about a buffer overflow for openjdk builds. Would appreciate it if you could have a look! :)

2017-06-08 08:19 UTC, SierraGolf commented
@Niaobu Thanks for contributing, I will have a look at your PR and give feedback on the weekend.

2017-06-19 08:05 UTC, SierraGolf requested changes

2017-06-19 08:05 UTC, SierraGolf commented on src/main/java/com/codereligion/bugsnag/logback/Converter.java
> +    private String convertToSeverity(final Level level) {
please format correctly  and consistently with spaces after `if`/`else` and before/after `(`/`)` and before/after `==`

2017-06-19 08:05 UTC, SierraGolf commented on src/test/java/com/codereligion/bugsnag/logback/integration/SerializationFullIntegrationTest.java
> +import static com.github.tomakehurst.wiremock.client.WireMock.*;
please follow the existing formatting, which is no * imports alphabetic order.

2017-06-19 08:05 UTC, SierraGolf commented on src/main/java/com/codereligion/bugsnag/logback/model/EventVO.java
> +    private String payloadVersion = "2";
did you test this implementation? looking at the current api documentation I think we need to change the following in the `EventVO` otherwise the properties will not be supported:

- userId => user.id
- appVersion => app.version
- releaseStage => app.releaseStage
- osVersion => device.osVersion

so we would need to add three new `VO`s: `UserVO`, `AppVO`, `DeviceVO`.

2017-06-19 08:05 UTC, SierraGolf commented on src/main/java/com/codereligion/bugsnag/logback/Converter.java
> +        return null;
OK, but I think we should update the README.md and make it clear that the logging levels: OFF, DEBUG, TRACE and ALL are currently not handled and will be sent to bugsnag as `null`

2019-11-28 13:31 UTC, closed without merging